/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Carro;
import model.dao.CarroDAO;

/**
 *
 * @author estudo
 */
public final class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroTabela
     */
    public TelaCadastro() {
        initComponents();
        
        // ORDENANDO A TABELA
        DefaultTableModel modelo = (DefaultTableModel) jTableCarros.getModel();
        jTableCarros.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTableCarros.getModel();
        modelo.setNumRows(0); // Acaba com a duplicação de valores.
        CarroDAO carroDao = new CarroDAO();

        for(Carro car: carroDao.read()) {

            modelo.addRow(new Object[]{
                car.getId(),
                car.getMarca(),
                car.getPlaca(),
                car.getCor(),
                car.getHoraEntrada(),
                car.getHoraSaida()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabelPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabelHoraEntrada = new javax.swing.JLabel();
        jLabelHoraSaida = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarros = new javax.swing.JTable();
        txtHoraEntrada = new javax.swing.JTextField();
        txtHoraSaida = new javax.swing.JTextField();
        jButton1Excluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de Cadastro");

        jLabel1.setText("Marca");

        jLabelPlaca.setText("Placa");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jLabelCor.setText("Cor");

        jLabelHoraEntrada.setText("Hora de Entrada");

        jLabelHoraSaida.setText("Hora de Saida");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTableCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_CARRO", "Marca", "Placa", "Cor", "Hora de Entrada", "Hora de Saida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCarros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jButton1Excluir.setText("Excluir");
        jButton1Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alteração");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHoraEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraEntrada)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHoraSaida)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraEntrada)
                    .addComponent(jLabelHoraSaida)
                    .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButton1Excluir)
                    .addComponent(jButtonAlterar))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // ADICIONANDO OS DADOS NA TABELA:
        
        Carro carro = new Carro();
        CarroDAO carroDao = new CarroDAO();
        
        carro.setMarca(txtMarca.getText());
        carro.setPlaca(txtPlaca.getText());
        carro.setCor(txtCor.getText());
        carro.setHoraEntrada(Integer.parseInt(txtHoraEntrada.getText()));
        carro.setHoraSaida(Integer.parseInt(txtHoraSaida.getText()));
        
        carroDao.create(carro);
        
        //LIMPADO OS CAMPOS APÓS CADASTRAR
        txtMarca.setText("");
        txtPlaca.setText("");
        txtCor.setText("");
        txtHoraEntrada.setText("");
        txtHoraSaida.setText("");
        
        readJTable();
        
      /*  
       DefaultTableModel dtmCarros = (DefaultTableModel) jTableCarros.getModel();
       Object[] dados = {txtMarca.getText(), txtPlaca.getText(),txtCor.getText(),txtHoraEntrada.getText(),txtHoraSaida.getText()};
       dtmCarros.addRow(dados);
      */  
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButton1ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExcluirActionPerformed
        // Excluindo itens da tabela:
        
        if(jTableCarros.getSelectedRow()!= -1){ // Significa que o usuário clicou em um item da tabela.
            Carro carro = new Carro();
            CarroDAO carroDao = new CarroDAO();

            carro.setId((int)jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 0));
            
            carroDao.delete(carro);

            //LIMPADO OS CAMPOS APÓS CADASTRAR
            txtMarca.setText("");
            txtPlaca.setText("");
            txtCor.setText("");
            txtHoraEntrada.setText("");
            txtHoraSaida.setText("");

            readJTable();
        }
         else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_jButton1ExcluirActionPerformed

    private void jTableCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrosMouseClicked
        // TODO add your handling code here:
        
        if(jTableCarros.getSelectedRow() != -1){
            txtMarca.setText(jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 0).toString());
            txtPlaca.setText(jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 1).toString());
            txtCor.setText(jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 2).toString());
            txtHoraEntrada.setText(jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 3).toString());
            txtHoraSaida.setText(jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jTableCarrosMouseClicked

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // ATUALIZANDO OS DADOS DA TABELA:
        
        if(jTableCarros.getSelectedRow() != -1){
            Carro carro = new Carro();
            CarroDAO carroDao = new CarroDAO();

            carro.setMarca(txtMarca.getText());
            carro.setPlaca(txtPlaca.getText());
            carro.setCor(txtCor.getText());
            carro.setHoraEntrada(Integer.parseInt(txtHoraEntrada.getText()));
            carro.setHoraSaida(Integer.parseInt(txtHoraSaida.getText()));
            carro.setId((int)jTableCarros.getValueAt(jTableCarros.getSelectedRow(), 0));
            
            carroDao.update(carro);

            //LIMPADO OS CAMPOS APÓS CADASTRAR
            txtMarca.setText("");
            txtPlaca.setText("");
            txtCor.setText("");
            txtHoraEntrada.setText("");
            txtHoraSaida.setText("");

            readJTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione o produto que deseja alterar.");
        }
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Excluir;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelHoraEntrada;
    private javax.swing.JLabel jLabelHoraSaida;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarros;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtHoraEntrada;
    private javax.swing.JTextField txtHoraSaida;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
